In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Breast_Cancer.csv')
df

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,Other,Married,T1,N1,IIA,Moderately differentiated,2,Regional,9,Positive,Positive,1,1,49,Alive
4020,56,White,Divorced,T2,N2,IIIA,Moderately differentiated,2,Regional,46,Positive,Positive,14,8,69,Alive
4021,68,White,Married,T2,N1,IIB,Moderately differentiated,2,Regional,22,Positive,Negative,11,3,69,Alive
4022,58,Black,Divorced,T2,N1,IIB,Moderately differentiated,2,Regional,44,Positive,Positive,11,1,72,Alive
4023,46,White,Married,T2,N1,IIB,Moderately differentiated,2,Regional,30,Positive,Positive,7,2,100,Alive

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoders = {}
for column in df.columns:
  le = LabelEncoder()
  df[column] = le.fit_transform(df[column])
  label_encoders[column] = le

In [ ]:
x=df.drop('Progesterone Status',axis=1)
y=df['Progesterone Status']

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x,y)

KNeighborsClassifier()

In [ ]:
print('now model is trained')

now model is trained

In [ ]:
new_data = pd.DataFrame({
    'Age': [68],
    'Race': ['White'],
    'Marital Status': ['Married'],
    'T Stage ': ['T1'],
    'N Stage': ['N1'],
    '6th Stage': ['IIA'],
    'differentiate': ['Poorly differentiated'],
    'Grade': [3],
    'A Stage': ['Regional'],
    'Tumor Size': [4],
    'Estrogen Status': ['Positive'],
    'Regional Node Examined': [24],
    'Reginol Node Positive': [1],
    'Survival Months': [60],
    'Status':['Alive']
})
new_data

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,24,1,60,Alive

In [ ]:
for col in new_data.select_dtypes(include='object').columns:
    if col in label_encoders:
        new_data[col] = label_encoders[col].transform(new_data[col])

In [ ]:
final_result = label_encoders['Progesterone Status'].inverse_transform(prediction)

print("""Predicted class (encoded):
Please check the 'Progesterone Status' to verify if it is correct.""",prediction)
print("""Predicted class (actual):
Please check the 'Progesterone Status' to verify if it is correct.""",final_result[0])

Predicted class (encoded):
Please check the 'Progesterone Status' to verify if it is correct. [1]
Predicted class (actual):
Please check the 'Progesterone Status' to verify if it is correct. Positive